APP_NAME = "Community Discussions API"
DEBUG_MODE = true
HOST = "0.0.0.0"
PORT = 8000
API_V1 = "/api/v1"
DB_URL = "mongodb+srv://<username>:<password>@<url>/<db>?retryWrites=true&w=majority"
DB_NAME = "communityDB"
