name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project
        working-directory: ./discussions-api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run linter
        working-directory: ./discussions-api
        run: make lint
      - name: Run tests
        working-directory: ./discussions-api
        run: make test
